name: workforce
description: A kreattech project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.1.1
  intl_phone_field: ^3.1.0
  iconly: ^1.0.1
  percent_indicator: ^4.2.2



flutter_native_splash:

  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove

  color: "#1b93fb"
  #background_image: "assets/background.png"

  image: assets/images/splash.png

  #branding: assets/dart.png
  #branding_mode: bottom

  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
  #branding_dark: assets/dart_dark.png

  android: true

  android_gravity: center


  fullscreen: true


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logos/
    - assets/images/money/


  fonts:
    - family: PermanentMarker
      fonts:
        - asset: assets/fonts/PermanentMarker-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Fredoka
      fonts:
  # - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-Bold.ttf

    - family: Yanone
      fonts:
  # - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/YanoneKaffeesatz-Regular.ttf

    - family: Josefin
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf

    - family: RadioCanada
      fonts:
        - asset: assets/fonts/RadioCanada-VariableFont_wdth,wght.ttf

    

